export const connectWallet = 'Connect your wallet'
export const collateralAssetNotSelected = 'Collateral asset is not selected'
export const borrowedAssetNotSelected = 'Borrowed asset is not selected'
export const depositAssetNotSelected = 'Deposit asset is not selected'
export const riskNotSelected = 'Target risk is not selected'
export const assetAddressNotDefined = 'Address does not defined for this asset'
