export const home = '/'
export const markets = '/app/markets'
export const deposit = '/app/deposit'
export const borrow = '/app/borrow'
export const dashboard = '/app/dashboard'
export const analytics = '/app/analytics'
export const repayment = '/app/repayment'
export const withdrawal = '/app/withdrawal'
